### ISSUE TITLE
Single column, app responsiveness fixes checklist

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#307]
**General**
- [x] Set minimum width to ~280 px~ 360 px (the standard we've now set for COSMIC apps. We'll need to check again with this narrower size)
- [x] Always collapse to the content. On first launch the app collapses to the NavBar. If I change the page in the NavBar, it seems to collapse to the content.

**Desktop and Panel > Panel**
- [ ] Wrap "Gap between panel and screen edges" so the toggle doesn't move
- [x] Size: wrap the slider to a second line
- [x] Background opacity: wrap the slider to a second line
- [x] Adding an applet isn't responsive but should be fixed on this [issue](https://github.com/pop-os/cosmic-settings/issues/301).

**Desktop and Panel > Dock**
- [ ] Wrap "Gap between dock and screen edges" so the toggle doesn't move
- [x] Size: wrap the slider to a second line
- [x] Background opacity: wrap the slider to a second line
- [x] Adding an applet isn't responsive but should be fixed on this [issue](https://github.com/pop-os/cosmic-settings/issues/301).

**Input Devices > Mouse**
- [x] "Primary button" Left|Right segmented button doesn't shrink well. Reducing the size of the label container seems because there's enough room. Alternatively, we can wrap the button to the second line.
- [x] Mouse speed: wrap the slider to the second line
- [x] Scrolling speed: wrap the slider to the second line

**Input Devices > Touchpad**
- [x] "Primary button" Left|Right segmented button doesn't shrink well. Reducing the size of the label container seems because there's enough room. Alternatively, we can wrap the button to the second line.
- [x] Touchpad speed: wrap the slider to the second line
- [ ] Scrolling speed: wrap the slider to the second line

**System & Accounts > About**
- [x] Device name entry should probably wrap to the second line.
The hardware section has odd wrapping but it's not a high priority. We can come back to it in a later release.

**Comment by mmstick** [comment]
Ready to review with commit 4ceac69

**Comment by WatchMkr** [comment]
Closing. A few more fixes are needed but I'll open separate issues.
